name: CI/CD
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      # uses: jenkey2011/vuepress-deploy@master
      uses: JamesIves/github-pages-deploy-action@master
      # with:
      #     BRANCH: main
      #     FOLDER: docs/.vuepress/dist
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: silin001.github.io
        TARGET_BRANCH: main
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist
        # CNAME: