name: vuepress CICD
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 获取源码
        uses: actions/checkout@v3
      - name: 安装node并指定版本
        uses: actions/setup-node@v3 # 安装node
        with:
          node-version: "16.x" # 指定node版本 不指定使用默认版本
      - run: yarn
      - run: yarn build
      - name: 部署到github-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs/.vuepress/dist # 部署打包后的 dist 目录
          github_token: ${{ secrets.DEPLOY_SECRET }} #  secret 名称
          commit_message: 自动部署(cicd) # 部署时的 git 提交信息，自由填写

      # 同步gitee
      # - name: Sync to Gitee
      #   uses: wearerequired/git-mirror-action@master
      #   env:
      #     # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
      #     SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      #   with:
      #     # 注意替换为你的 GitHub 源仓库地址
      #     source-repo: git@github.com:silin001/docs.git
      #     # 注意替换为你的 Gitee 目标仓库地址
      #     destination-repo: git@gitee.com:sisi001/docs.git

      - name: Sync to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: "github/silin001"
          dst: "gitee/sisi001"
          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          dst_token: ${{ secrets.DEPLOY_SECRET }}
          static_list: "learn-typescript"
          force_update: true
          debug: true
      # gitee自动部署
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: sisi001
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: sisi001/docs
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh-pages
