# name: deploy
# on: [push]  // 推送代码触发脚本
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@master

#     - name: vuepress-deploy
#       uses: jenkey2011/vuepress-deploy@master
#       env:
#         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} // github Token
#         TARGET_REPO: silin001/silin001.github.io  // 仓库

#         TARGET_BRANCH: main    // build 之后推到的分支名
#         BUILD_SCRIPT: yarn && yarn build
#         BUILD_DIR: src/.vuepress/dist/     //build 之后的目录


name: vuepress CICD
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 获取源码
        uses: actions/checkout@v3
       #步骤2  安装node并指定版本
      - name: 安装node并指定版本
        uses: actions/setup-node@v3 # 安装node
        with:
          node-version: "16.x" # 指定node版本 不指定使用默认版本
      - name: -----测试输出
        run: |
          node -v
          npm -v
          echo '哈哈哈哈'

      - name: 下载依赖和打包
        run: |
          npm install
          npm run build

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist